### PR TITLE
add support  for kernel 5.6.0

### LINKED ISSUE #65: fail to compile with kernel 5.6.0 rcX
There it is:
  CC [M]  /root/asus/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959/os_dep/linux/rtw_proc.o
/root/asus/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959/os_dep/linux/rtw_proc.c: In function ‘rtw_proc_create_entry’:
/root/asus/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959/os_dep/linux/rtw_proc.c:70:71: error: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   70 |  entry = proc_create_data(name,  S_IFREG | S_IRUGO | S_IWUGO, parent, fops, data);
      |                                                                       ^~~~
      |                                                                       |
      |                                                                       const struct file_operations *
In file included from /root/asus/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959/include/../os_dep/linux/rtw_proc.h:18,
                 from /root/asus/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959/include/osdep_intf.h:128,
                 from /root/asus/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959/include/drv_types.h:105,
                 from /root/asus/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959/os_dep/linux/rtw_proc.c:17:
./include/linux/proc_fs.h:61:13: note: expected ‘const struct proc_ops *’ but argument is of type ‘const struct file_operations *’
   61 |             const struct proc_ops *,
      |             ^~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:268: /root/asus/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959/os_dep/linux/rtw_proc.o] Error 1
make[1]: *** [Makefile:1683: /root/asus/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.6.0-0.rc5.git0.2.fc32.x86_64'
make: *** [Makefile:2011: modules] Error 2

----------------------------------------------UPDATE----------------------------------------------------
I solved it, changed the code and works fine, i used the 5.6.1 clone as basis, but I have no idea how to clone with git etc. Do you want me to upload somehow the code?

### PR DESCRIPTION
**Pull request by karubabu**
fix: https://github.com/cilynx/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959/issues/65
ref: https://github.com/torvalds/linux/commit/97a32539b9568bb653683349e5a76d02ff3c3e2c

### CODE REVIEW

**Comment by cilynx** [comment]
Thank you!
