### ISSUE TITLE
Error with DKMS build

### ISSUE THREAD

**Issue by kitkat270** [cilynx/rtl88x2bu#13]
Really stuck with this problem on RPi 3B. I'm not a software dev and have spent the last 4 hours googling trying to get this adaptor working... 

`pi@raspberrypi:~/Desktop/rtl88x2bu $ sudo dkms build -m rtl88x2bu -v ${VER}`

Kernel preparation unnecessary for this kernel.  Skipping...
Building module:
cleaning build area...
make -j4 KERNELRELEASE=4.19.97-v7+ KVER=4.19.97-v7+ src=/usr/src/rtl88x2bu-5.6.1..........(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.19.97-v7+ (armv7l)
Consult /var/lib/dkms/rtl88x2bu/5.6.1/build/make.log for more information

DKMS make.log for rtl88x2bu-5.6.1 for kernel 4.19.97-v7+ (armv7l)
Sun  9 Feb 19:54:25 GMT 2020
/bin/sh: 1: bc: not found
make ARCH=arm CROSS_COMPILE= -C /lib/modules/4.19.97-v7+/build M=/var/lib/dkms/rtl88x2bu/5.6.1/build  modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.97-v7+'
/bin/sh: 1: bc: not found
  CC [M]  /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_io.o
/usr/src/rtl88x2bu-5.6.1/core/rtw_debug.c: In function ‘dump_drv_version’:
/usr/src/rtl88x2bu-5.6.1/core/rtw_debug.c:45:62: error: macro "__DATE__" might prevent reproducible builds [-Werror=date-time]
  RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
                                                              ^
/usr/src/rtl88x2bu-5.6.1/core/rtw_debug.c:45:62: error: macro "__TIME__" might prevent reproducible builds [-Werror=date-time]
/usr/src/rtl88x2bu-5.6.1/core/rtw_debug.c:45:62: error: macro "__DATE__" might prevent reproducible builds [-Werror=date-time]
/usr/src/rtl88x2bu-5.6.1/core/rtw_debug.c:45:62: error: macro "__TIME__" might prevent reproducible builds [-Werror=date-time]
  CC [M]  /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_ioctl_query.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_ieee80211.o
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:303: /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_debug.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1522: _module_/var/lib/dkms/rtl88x2bu/5.6.1/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.97-v7+'
make: *** [Makefile:2270: modules] Error 2

Thanks for any help :-)

**Comment by cilynx** [comment]
Looks like it's missing `bc`, which can be installed on the Pi via `sudo apt-get install bc`.  Did you wind up getting it working?
