### ISSUE TITLE
Issue bulding module for 5.10.0-kali4-amd64

### ISSUE THREAD

**Issue by Sticatel** [cilynx/rtl88x2bu#135]
Following the instructions in the build step I get the following error:

```
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.10.0-kali4-amd64 KVER=5.10.0-kali4-amd64 src=/usr/src/rtl88x2bu-5.6.1....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.10.0-kali4-amd64 (x86_64)
Consult /var/lib/dkms/rtl88x2bu/5.6.1/build/make.log for more information.
```
This is the make.log

```
DKMS make.log for rtl88x2bu-5.6.1 for kernel 5.10.0-kali4-amd64 (x86_64)
Thu 11 Mar 2021 07:01:12 AM EST
/bin/sh: 1: bc: not found
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.10.0-kali4-amd64/build M=/var/lib/dkms/rtl88x2bu/5.6.1/build  modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.0-kali4-amd64'
/bin/sh: 1: bc: not found
  CC [M]  /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_io.o
/usr/src/rtl88x2bu-5.6.1/core/rtw_debug.c: In function ‘dump_drv_version’:
/usr/src/rtl88x2bu-5.6.1/core/rtw_debug.c:45:62: error: macro "__DATE__" might prevent reproducible builds [-Werror=date-time]
   45 |  RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
      |                                                              ^
In file included from /usr/src/rtl88x2bu-5.6.1/include/drv_types.h:60,
                 from /usr/src/rtl88x2bu-5.6.1/core/rtw_debug.c:17:
/usr/src/rtl88x2bu-5.6.1/core/rtw_debug.c:45:44: error: macro "__TIME__" might prevent reproducible builds [-Werror=date-time]
   45 |  RTW_PRINT_SEL(sel, "build time: %s %s\n", __DATE__, __TIME__);
      |                                            ^~~~~~~~
/usr/src/rtl88x2bu-5.6.1/include/rtw_debug.h:224:25: note: in definition of macro ‘RTW_PRINT_SEL’
  224 |    _seqdump(sel, fmt, ##arg) /*rtw_warn_on(1)*/; \
      |                         ^~~
  CC [M]  /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_ioctl_query.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_ieee80211.o
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-5.10.0-kali4-common/scripts/Makefile.build:284: /var/lib/dkms/rtl88x2bu/5.6.1/build/core/rtw_debug.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/src/linux-headers-5.10.0-kali4-common/Makefile:1813: /var/lib/dkms/rtl88x2bu/5.6.1/build] Error 2
make[1]: *** [/usr/src/linux-headers-5.10.0-kali4-common/Makefile:185: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.0-kali4-amd64'
make: *** [Makefile:2284: modules] Error 2
```
I used the default 5.6.1 branch

**Comment by UbuntuStrike** [comment]
If you look at the error log you see "/bin/sh: 1: bc: not found" ?
apt install bc
clean out previous install attempt then try again... I had the same issue on Kali but its working now with 5.6.1
